# See: https://github.com/bradennapier/eslint-plus-action

name: "ESLint"
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          issueSummaryType: full
          reportIgnoredFiles: true
          reportWarningsAsErrors: true
