name: Bump, Release, and Publish

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: "Bump Type (major minor patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: tag-and-release
  cancel-in-progress: true

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
          token: ${{ secrets.VERSION_BUMP_TAG_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: NPM Clean Install
        run: npm ci
      - name: NPM Run Build
        run: npm run build --if-present
      - name: NPM Test
        run: npm test
        env:
          CI: true
      - name: Bump, Release, and Publish
        uses: bcomnes/npm-bump@v2
        with:
          git_email: david@davidlday.com
          git_username: ${{ github.actor }}
          newversion: ${{ github.event.inputs.newversion }}
          push_version_commit: true
          github_token: ${{ secrets.VERSION_BUMP_TAG_TOKEN }}
          npm_token: ${{secrets.NPM_ACCESS_TOKEN}}
